# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
<html>
<heder>
<title> raj fuk you </title>
</heder>
<body bgcolor="#550203"> 
 
										
	<center>
<b>
<i><font color="red and blue"> <h1>  yazan+maykel couple </h1> </font> </i>
<br/>
<font color= "blue" size=5>www.maykel_.com </font>

<br/>
<font color= "pink" size=5>for  video <input type="button" value="clıke her"/>
	
</b>
	
</ceenter>
<div style="text-align: left"/> 
		<i><font color=#000000 size="10"></i> I love the way u explore my body <h1>  </font></h1>
		<img src="yazan.jpg"/> 
		
		<dr/>
		<i><font color=#000000 size="10"></i>	I want to feel your skin against mine every night
		<div style="text-align: right"/> 
		<img src="IMG-20200722-WA0001.jpg">
		
</body>
</html>
